### ISSUE TITLE
Spelling error in the readme.md

### ISSUE THREAD

**Issue by vaibhavkumawat-17** [vaidyanathaniyer/vaidyanathaniyer#1]
- 💻 𝙾𝚂: 𝚖𝚊𝚌𝙾𝚂 𝟷𝟺, 𝙰𝚗𝚍𝚛𝚘𝚒𝚍
- ⏱️ 𝚄𝚙𝚝𝚒𝚖𝚎: 𝟷𝟾 𝚢𝚎𝚊𝚛𝚜
- 🏢 𝙷𝚘𝚜𝚝: 𝙽𝚊𝚟𝚛𝚊𝚌𝚑𝚊𝚗𝚊 𝚄𝚗𝚒𝚟𝚎𝚛𝚜𝚒𝚝𝚢 #𝙽𝚄𝚅
- 💡 𝙺𝚎𝚛𝚗𝚎𝚕: 𝙲𝚘𝚖𝚙𝚞𝚝𝚎𝚛 𝚂𝚌𝚒𝚎𝚗𝚌𝚎 𝚊𝚗𝚍 𝙴𝚗𝚐𝚒𝚗𝚎𝚎𝚛𝚒𝚗𝚐 #𝙱𝚃𝙴𝙲𝙷-𝙲𝚂𝙴
- 🖥️ 𝙸𝙳𝙴: 𝚅𝚂𝙲𝚘𝚍𝚎 𝟷.𝟾𝟹, 𝙰𝚗𝚍𝚛𝚘𝚒𝚍 𝚂𝚝𝚞𝚍𝚒𝚘 (𝙶𝚒𝚛𝚊𝚏𝚏𝚎)
- 👨‍💻 𝙻𝚊𝚗𝚐𝚞𝚊𝚐𝚎𝚜.𝙿𝚛𝚘𝚐𝚛𝚊𝚖𝚖𝚒𝚗𝚐: 𝙿𝚢𝚝𝚑𝚘𝚗, 𝙲, 𝙹𝚊𝚟𝚊, 𝙺𝚘𝚝𝚕𝚒𝚗
- 💻 𝙻𝚊𝚗𝚐𝚞𝚊𝚐𝚎𝚜.𝙲𝚘𝚖𝚙𝚞𝚝𝚎𝚛: 𝙷𝚃𝙼𝙻, 𝙲𝚂𝚂, 𝚇𝙼𝙻, 𝙻𝚊𝚃𝚎𝚇, 𝙼𝚊𝚛𝚔𝚍𝚘𝚠𝚗
- 🗣️ 𝙻𝚊𝚗𝚐𝚞𝚊𝚐𝚎𝚜.𝚁𝚎𝚊𝚕: 𝙴𝚗𝚐𝚕𝚒𝚜𝚑, 𝙷𝚒𝚗𝚍𝚒, 𝚃𝚊𝚖𝚒𝚕
- 🚀 𝙷𝚘𝚋𝚋𝚒𝚎𝚜.𝚂𝚘𝚏𝚝𝚠𝚊𝚛𝚎: 𝙿𝚢𝚝𝚑𝚘𝚗𝚒𝚜𝚝𝚊, 𝙲𝚛𝚊𝚏𝚝𝚒𝚗𝚐 𝙰𝚗𝚍𝚛𝚘𝚒𝚍 & 𝚒𝙾𝚂 𝙰𝚙𝚙𝚜
- 🛠️ 𝙷𝚘𝚋𝚋𝚒𝚎𝚜.𝙷𝚊𝚛𝚍𝚠𝚊𝚛𝚎: 𝙰𝚛𝚍𝚞𝚒𝚗𝚘 **_𝚃𝚒𝚗𝚔𝚎𝚛𝚎𝚛_** 

you can see the spelling error in tinkerer, also no comma is there, fix this issue ASAP

**Comment by vaidyanathaniyer** [comment]
Thanks for your contribution! Regarding the "tinkerer" issue, it has been correctly spelled. There seems to be a misunderstanding. No grammatical error there. Appreciate your attention to detail. Feel free to raise any other concerns.
